BEGIN;

-- =========================================================
-- TIPOS REQUERIDOS
-- =========================================================

CREATE TYPE scheme_status AS ENUM (
  'DRAFT',
  'LOCATIONS_DEFINED',
  'PARTIALLY_ASSIGNED',
  'ASSIGNED'
);

-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users (
  user_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       VARCHAR(60) NOT NULL,
  email          VARCHAR(255) NOT NULL,
  password_hash  VARCHAR(255) NOT NULL,
  full_name      VARCHAR(120) NOT NULL,
  enabled        BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at  TIMESTAMPTZ,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT users_username_not_blank
    CHECK (btrim(username) <> ''),

  CONSTRAINT users_email_not_blank
    CHECK (btrim(email) <> ''),

  CONSTRAINT users_password_hash_not_blank
    CHECK (btrim(password_hash) <> ''),

  CONSTRAINT users_full_name_not_blank
    CHECK (btrim(full_name) <> '')
);


-- =========================================================
-- SCHEMES
-- =========================================================

CREATE TABLE schemes (
  scheme_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 VARCHAR(80) NOT NULL,
  status               scheme_status NOT NULL DEFAULT 'DRAFT',
  short_description    VARCHAR(255),
  map_svg              TEXT,
  is_active            BOOLEAN NOT NULL DEFAULT false,
  enabled              BOOLEAN NOT NULL DEFAULT true,
  created_by           INTEGER,
  published_by         INTEGER,
  published_at         TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT schemes_name_not_blank
    CHECK (btrim(name) <> ''),

  CONSTRAINT schemes_map_svg_not_blank
    CHECK (
      map_svg IS NULL
      OR btrim(map_svg) <> ''
    ),

  CONSTRAINT schemes_active_valid
    CHECK (
      NOT is_active
      OR (enabled AND status = 'ASSIGNED')
    ),

  CONSTRAINT schemes_publication_metadata_complete
    CHECK (
      (published_by IS NULL AND published_at IS NULL)
      OR (
        published_by IS NOT NULL
        AND published_at IS NOT NULL
        AND status = 'ASSIGNED'
      )
    ),

  CONSTRAINT schemes_created_by_fkey
    FOREIGN KEY (created_by)
    REFERENCES users (user_id),

  CONSTRAINT schemes_published_by_fkey
    FOREIGN KEY (published_by)
    REFERENCES users (user_id)
);


-- =========================================================
-- LOCATIONS
-- =========================================================

CREATE TABLE locations (
  location_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id               INTEGER NOT NULL,
  parent_location_id      INTEGER,
  level                   SMALLINT NOT NULL,
  level_name              VARCHAR(60) NOT NULL,
  level_name_override     VARCHAR(60),
  name                    VARCHAR(70) NOT NULL,
  code                    VARCHAR(120) NOT NULL,
  sort_order              SMALLINT NOT NULL,
  range_start_raw         VARCHAR(120),
  range_end_raw           VARCHAR(120),
  range_start_key         BYTEA,
  range_end_key           BYTEA,
  created_by              INTEGER,
  updated_by              INTEGER,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT locations_scheme_location_unique
    UNIQUE (scheme_id, location_id),

  CONSTRAINT locations_scheme_code_unique
    UNIQUE (scheme_id, code),

  CONSTRAINT locations_name_not_blank
    CHECK (btrim(name) <> ''),

  CONSTRAINT locations_code_not_blank
    CHECK (btrim(code) <> ''),

  CONSTRAINT locations_sibling_sort_unique
    UNIQUE NULLS NOT DISTINCT (scheme_id, parent_location_id, sort_order)
    DEFERRABLE INITIALLY IMMEDIATE,

  CONSTRAINT locations_sort_positive
    CHECK (sort_order > 0),

  CONSTRAINT locations_level_positive
    CHECK (level > 0),

  CONSTRAINT locations_level_name_not_blank
    CHECK (btrim(level_name) <> ''),

  CONSTRAINT locations_level_name_override_not_blank
    CHECK (
      level_name_override IS NULL
      OR btrim(level_name_override) <> ''
    ),

  CONSTRAINT locations_not_self_parent
    CHECK (
      parent_location_id IS NULL
      OR parent_location_id <> location_id
    ),

  CONSTRAINT locations_range_complete
    CHECK (
      (
        range_start_raw IS NULL
        AND range_end_raw IS NULL
        AND range_start_key IS NULL
        AND range_end_key IS NULL
      )
      OR
      (
        range_start_raw IS NOT NULL
        AND range_end_raw IS NOT NULL
        AND range_start_key IS NOT NULL
        AND range_end_key IS NOT NULL
        AND range_start_key <= range_end_key
      )
    ),

  CONSTRAINT locations_scheme_fkey
    FOREIGN KEY (scheme_id)
    REFERENCES schemes (scheme_id),

  CONSTRAINT locations_parent_same_scheme_fkey
    FOREIGN KEY (scheme_id, parent_location_id)
    REFERENCES locations (scheme_id, location_id)
    DEFERRABLE INITIALLY IMMEDIATE,

  CONSTRAINT locations_created_by_fkey
    FOREIGN KEY (created_by)
    REFERENCES users (user_id),

  CONSTRAINT locations_updated_by_fkey
    FOREIGN KEY (updated_by)
    REFERENCES users (user_id)
);


COMMIT;
