BEGIN;

-- =========================================================
-- TIPOS REQUERIDOS
-- =========================================================

CREATE TYPE scheme_status AS ENUM (
  'DRAFT',
  'LEVELS_DEFINED',
  'LOCATIONS_DEFINED',
  'PARTIALLY_ASSIGNED',
  'ASSIGNED'
);

CREATE TYPE map_layer_type AS ENUM (
  'TOP',
  'FRONT',
  'OTHER'
);

CREATE TYPE map_render_mode AS ENUM (
  'STATIC',
  'TEMPLATE'
);


-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users (
  user_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       VARCHAR(60) NOT NULL,
  email          VARCHAR(255) NOT NULL,
  password_hash  VARCHAR(255) NOT NULL,
  full_name      VARCHAR(120) NOT NULL,
  enabled        BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at  TIMESTAMPTZ,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT users_username_not_blank
    CHECK (btrim(username) <> ''),

  CONSTRAINT users_email_not_blank
    CHECK (btrim(email) <> ''),

  CONSTRAINT users_password_hash_not_blank
    CHECK (btrim(password_hash) <> ''),

  CONSTRAINT users_full_name_not_blank
    CHECK (btrim(full_name) <> '')
);


-- =========================================================
-- SCHEMES
-- =========================================================

CREATE TABLE schemes (
  scheme_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 VARCHAR(80) NOT NULL,
  status               scheme_status NOT NULL DEFAULT 'DRAFT',
  short_description    VARCHAR(255),
  is_active            BOOLEAN NOT NULL DEFAULT false,
  enabled              BOOLEAN NOT NULL DEFAULT true,
  ordering_profile_id  INTEGER NOT NULL,
  created_by           INTEGER,
  published_by         INTEGER,
  published_at         TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT schemes_name_not_blank
    CHECK (btrim(name) <> ''),

  CONSTRAINT schemes_active_valid
    CHECK (
      NOT is_active
      OR (enabled AND status = 'ASSIGNED')
    ),

  CONSTRAINT schemes_publication_metadata_complete
    CHECK (
      (published_by IS NULL AND published_at IS NULL)
      OR (
        published_by IS NOT NULL
        AND published_at IS NOT NULL
        AND status = 'ASSIGNED'
      )
    ),

  CONSTRAINT schemes_ordering_profile_fkey
    FOREIGN KEY (ordering_profile_id)
    REFERENCES ordering_profiles (ordering_profile_id),

  CONSTRAINT schemes_created_by_fkey
    FOREIGN KEY (created_by)
    REFERENCES users (user_id),

  CONSTRAINT schemes_published_by_fkey
    FOREIGN KEY (published_by)
    REFERENCES users (user_id)
);


-- =========================================================
-- SCHEME_LEVELS
-- =========================================================

CREATE TABLE scheme_levels (
  scheme_level_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id           INTEGER NOT NULL,
  parent_level_id     INTEGER,
  name                VARCHAR(60) NOT NULL,
  sort_order          SMALLINT NOT NULL DEFAULT 0,
  is_search_terminal  BOOLEAN NOT NULL DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT scheme_levels_scheme_level_unique
    UNIQUE (scheme_id, scheme_level_id),

  CONSTRAINT scheme_levels_name_not_blank
    CHECK (btrim(name) <> ''),

  CONSTRAINT scheme_levels_sort_nonnegative
    CHECK (sort_order >= 0),

  CONSTRAINT scheme_levels_not_self_parent
    CHECK (
      parent_level_id IS NULL
      OR parent_level_id <> scheme_level_id
    ),

  CONSTRAINT scheme_levels_scheme_fkey
    FOREIGN KEY (scheme_id)
    REFERENCES schemes (scheme_id),

  CONSTRAINT scheme_levels_parent_same_scheme_fkey
    FOREIGN KEY (scheme_id, parent_level_id)
    REFERENCES scheme_levels (scheme_id, scheme_level_id)
    DEFERRABLE INITIALLY IMMEDIATE
);


-- =========================================================
-- LOCATIONS
-- =========================================================

CREATE TABLE locations (
  location_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id               INTEGER NOT NULL,
  parent_location_id      INTEGER,
  scheme_level_id         INTEGER NOT NULL,
  name                    VARCHAR(70) NOT NULL,
  code                    VARCHAR(120) NOT NULL,
  sort_order              SMALLINT NOT NULL DEFAULT 0,
  range_start_raw         VARCHAR(120),
  range_end_raw           VARCHAR(120),
  range_start_normalized  JSONB,
  range_end_normalized    JSONB,
  range_start_key         BYTEA,
  range_end_key           BYTEA,
  created_by              INTEGER,
  updated_by              INTEGER,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT locations_scheme_location_unique
    UNIQUE (scheme_id, location_id),

  CONSTRAINT locations_scheme_code_unique
    UNIQUE (scheme_id, code),

  CONSTRAINT locations_name_not_blank
    CHECK (btrim(name) <> ''),

  CONSTRAINT locations_code_not_blank
    CHECK (btrim(code) <> ''),

  CONSTRAINT locations_sort_nonnegative
    CHECK (sort_order >= 0),

  CONSTRAINT locations_not_self_parent
    CHECK (
      parent_location_id IS NULL
      OR parent_location_id <> location_id
    ),

  CONSTRAINT locations_normalized_objects
    CHECK (
      (
        range_start_normalized IS NULL
        OR jsonb_typeof(range_start_normalized) = 'object'
      )
      AND
      (
        range_end_normalized IS NULL
        OR jsonb_typeof(range_end_normalized) = 'object'
      )
    ),

  CONSTRAINT locations_range_complete
    CHECK (
      (
        range_start_raw IS NULL
        AND range_end_raw IS NULL
        AND range_start_normalized IS NULL
        AND range_end_normalized IS NULL
        AND range_start_key IS NULL
        AND range_end_key IS NULL
      )
      OR
      (
        range_start_raw IS NOT NULL
        AND range_end_raw IS NOT NULL
        AND range_start_normalized IS NOT NULL
        AND range_end_normalized IS NOT NULL
        AND range_start_key IS NOT NULL
        AND range_end_key IS NOT NULL
        AND range_start_key <= range_end_key
      )
    ),

  CONSTRAINT locations_scheme_fkey
    FOREIGN KEY (scheme_id)
    REFERENCES schemes (scheme_id),

  CONSTRAINT locations_level_same_scheme_fkey
    FOREIGN KEY (scheme_id, scheme_level_id)
    REFERENCES scheme_levels (scheme_id, scheme_level_id)
    DEFERRABLE INITIALLY IMMEDIATE,

  CONSTRAINT locations_parent_same_scheme_fkey
    FOREIGN KEY (scheme_id, parent_location_id)
    REFERENCES locations (scheme_id, location_id)
    DEFERRABLE INITIALLY IMMEDIATE,

  CONSTRAINT locations_created_by_fkey
    FOREIGN KEY (created_by)
    REFERENCES users (user_id),

  CONSTRAINT locations_updated_by_fkey
    FOREIGN KEY (updated_by)
    REFERENCES users (user_id)
);


-- =========================================================
-- MAP_LAYERS
-- =========================================================

CREATE TABLE map_layers (
  map_layer_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id     INTEGER NOT NULL,
  name          VARCHAR(120) NOT NULL,
  view_type     map_layer_type NOT NULL,
  render_mode   map_render_mode NOT NULL,
  enabled       BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT map_layers_scheme_layer_unique
    UNIQUE (scheme_id, map_layer_id),

  CONSTRAINT map_layers_name_not_blank
    CHECK (btrim(name) <> ''),

  CONSTRAINT map_layers_scheme_fkey
    FOREIGN KEY (scheme_id)
    REFERENCES schemes (scheme_id)
);


-- =========================================================
-- MAP_LAYER_SCHEME_LEVELS
-- =========================================================

CREATE TABLE map_layer_scheme_levels (
  map_layer_id            INTEGER NOT NULL,
  scheme_level_id         INTEGER NOT NULL,
  drilldown_map_layer_id  INTEGER,

  CONSTRAINT map_layer_scheme_levels_pkey
    PRIMARY KEY (map_layer_id, scheme_level_id),

  CONSTRAINT map_layer_scheme_levels_no_self_drilldown
    CHECK (
      drilldown_map_layer_id IS NULL
      OR drilldown_map_layer_id <> map_layer_id
    ),

  CONSTRAINT map_layer_scheme_levels_layer_fkey
    FOREIGN KEY (map_layer_id)
    REFERENCES map_layers (map_layer_id)
    ON DELETE CASCADE,

  CONSTRAINT map_layer_scheme_levels_level_fkey
    FOREIGN KEY (scheme_level_id)
    REFERENCES scheme_levels (scheme_level_id),

  CONSTRAINT map_layer_scheme_levels_drilldown_fkey
    FOREIGN KEY (drilldown_map_layer_id)
    REFERENCES map_layers (map_layer_id)
    ON DELETE SET NULL
);


-- =========================================================
-- MAP_LAYER_SVGS
-- =========================================================

CREATE TABLE map_layer_svgs (
  map_layer_svg_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  map_layer_id      INTEGER NOT NULL,
  name              VARCHAR(120) NOT NULL,
  variant_code      VARCHAR(60),
  asset_url         TEXT NOT NULL,
  slot_count        SMALLINT,
  enabled           BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT map_layer_svgs_layer_svg_unique
    UNIQUE (map_layer_id, map_layer_svg_id),

  CONSTRAINT map_layer_svgs_variant_unique
    UNIQUE (map_layer_id, variant_code),

  CONSTRAINT map_layer_svgs_name_not_blank
    CHECK (btrim(name) <> ''),

  CONSTRAINT map_layer_svgs_url_not_blank
    CHECK (btrim(asset_url) <> ''),

  CONSTRAINT map_layer_svgs_variant_not_blank
    CHECK (
      variant_code IS NULL
      OR btrim(variant_code) <> ''
    ),

  CONSTRAINT map_layer_svgs_slot_count_positive
    CHECK (
      slot_count IS NULL
      OR slot_count > 0
    ),

  CONSTRAINT map_layer_svgs_layer_fkey
    FOREIGN KEY (map_layer_id)
    REFERENCES map_layers (map_layer_id)
    ON DELETE CASCADE
);


-- =========================================================
-- MAP_LAYER_SVG_ASSIGNMENTS
-- =========================================================

CREATE TABLE map_layer_svg_assignments (
  map_layer_id        INTEGER NOT NULL,
  map_layer_svg_id    INTEGER NOT NULL,
  context_location_id INTEGER NOT NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT map_layer_svg_assignments_pkey
    PRIMARY KEY (map_layer_id, context_location_id),

  CONSTRAINT map_layer_svg_assignments_svg_fkey
    FOREIGN KEY (map_layer_id, map_layer_svg_id)
    REFERENCES map_layer_svgs (map_layer_id, map_layer_svg_id)
    ON DELETE CASCADE,

  CONSTRAINT map_layer_svg_assignments_location_fkey
    FOREIGN KEY (context_location_id)
    REFERENCES locations (location_id)
    ON DELETE CASCADE
);

COMMIT;